---
- hosts: all
  sudo: yes
  tasks:
    - name: Install OS packages
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - python-pip
        - libxml2-dev
        - libxslt-dev
        - python-dev
        - python-lxml
        - libz-dev
        - git
    - name: Install Python packages
      shell: "pip install {{ item }}"
      with_items:
        - flask
        - lxml
        - BeautifulSoup4
    - git: repo=https://github.com/UMD-DCIC/LHARP.git dest=/home/ubuntu/LHARP version=master update=yes
    - command: python dashboard.py &
      args:
        chdir: /vagrant
  handlers:
    - name: restart Nginx
      service: name=ntpd state=restarted
